typography_spectrum: 0.8810504130087793
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.28883566870354116
  lightness: 0.9125265670008957
  saturation: 0.839615108910948
  rhythmicContrast: 0.507117829285562
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3377579851076007
analytics:
  google: null
  facebook: null
  twitter: null
name: Safari Eye
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: SAFARI EYES BTS .mp4
    id: 9b62ee84-fbf9-4f63-9093-d7343b899faf
    type: content
favicon: null
title: 'FILM &PHOTOGRAPHY WORKSHOPS '
description: Shoot to thrill!
purpose: []
