typography_spectrum: 0.52046
color:
  brandColors:
    - '#010101'
    - '#f9f8fb'
    - '#c9b49d'
    - '#b51917'
    - '#4b6566'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24169
analytics:
  google: null
  facebook: null
  twitter: null
name: Safari Eye
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'PHOTOGRAPHY EVENTS '
purpose: []
