typography_spectrum: 0.533173265401274
color:
  brandColors:
    - '#CFC291'
    - '#FFF6C5'
    - '#A1E8D9'
    - '#FF712C'
    - '#695D46'
  brandStrength: 0.1710245453286916
  lightness: 0.6464404312428087
  saturation: 0.334979209350422
  rhythmicContrast: 0.79866201733239
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2504913068842143
analytics:
  google: null
  facebook: null
  twitter: null
name: Safari Eye
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: SAFARI EYES BTS .mp4
    id: 9b62ee84-fbf9-4f63-9093-d7343b899faf
    type: content
favicon: null
title: 'FILM &PHOTOGRAPHY WORKSHOPS '
description: Shoot to thrill!
purpose: []
