name: Safari Eye
favicon: null
layout_spectrum: 0.24169
typography_spectrum: 0.52046
title: 'PHOTOGRAPHY EVENTS '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#f9f8fb'
    - '#c9b49d'
    - '#b51917'
    - '#4b6566'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
