name: Safari Eye
favicon: null
layout_spectrum: 0.6209165302570909
typography_spectrum: 0.2003014583606273
title: 'PHOTOGRAPHY EVENTS '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#545550'
    - '#858585'
    - '#c0a989'
    - '#fee8d2'
  brandStrength: 0.8125
  lightness: 0.3869283003732562
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
