name: Safari Eye
favicon: null
layout_spectrum: 0.24169
typography_spectrum: 0.52046
title: 'PHOTOGRAPHY EVENTS '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#545550'
    - '#858585'
    - '#c0a989'
    - '#fee8d2'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
